name: Test package in conda environment

on: [workflow_dispatch]

jobs:
    test-conda:
      name: Test with conda environment
      runs-on: "ubuntu-latest"
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.8", "3.11"]
      steps:
        - uses: actions/checkout@v5
        - uses: conda-incubator/setup-miniconda@v3
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
        - name: Conda install fenics
          shell: bash -el {0}
          run: conda install -c conda-forge fenics

        - name: Upgrade pip
          shell: bash -l {0}
          run: python3 -m pip install --upgrade pip

        - name: Install package
          shell: bash -l {0}
          run: python3 -m pip install -e .[test]

        - name: Run tests
          shell: bash -l {0}
          run: python3 -m pytest --cov=beat --cov-report=html --cov-report=term-missing -v
